# Generated by Django 5.0.6 on 2024-05-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_rename_time_category_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='createdby',
            new_name='created_by',
        ),
    ]
