# Generated by Django 5.0.6 on 2024-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_rename_create_category_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40)),
                ('emai', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='static/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos')),
            ],
        ),
    ]
