# Generated by Django 5.0.6 on 2024-05-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Image',
            new_name='images',
        ),
    ]
